name: Instagram Trend Analyzer

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  scrape-instagram:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright textblob supabase

      - name: Install Playwright browsers
        run: |
          playwright install chromium
          playwright install-deps chromium

      - name: Download TextBlob Corpora
        run: python -m textblob.download_corpora

      - name: Run Instagram Scraper
        run: python instagram_scraper.py
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        timeout-minutes: 45

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instagram-results
          path: |
            *.png
            *.log
          retention-days: 7